### ISSUE TITLE
feature28/History-Index

### ISSUE THREAD

**Issue by jojunicorn** [danka689681/TheFestival#27]
- [x]  make it dynamic
- [x] schedule

**Comment by jojunicorn** [comment]
Main content PR #29

**Comment by jojunicorn** [comment]
- [ ] make it dynamic
- [ ] schedule
- [ ] interactive map

**Comment by jojunicorn** [comment]
dynamic content PR #81

**Comment by jojunicorn** [comment]
content fixes PR #84

**Comment by danka689681** [comment]
History event info: PR #90
